### ISSUE TITLE
Great project! please add tsv and txt file for this project.

### ISSUE THREAD

**Issue by ha7sh17** [JudePark96/Korean-News-Classification#1]
Hi there!
I'm sure a lot of people want to run your project.
Could you add the newsdataCombined.tsv and NewsAllW2vec.txt file to repository ?
I would like to see as run-time.

Best Regards
ha7sh17

**Comment by JudePark96** [comment]
Unfortunately, I don't have a dataset anymore. I recommend you constructing experiment environment with other dataset such as 20newsgroups.

To fetch 20newsgroups dataset, `from sklearn.datasets import fetch_20newsgroups`.
Thanks.
